id: 485e7cab-131e-40ce-9482-791e681b7967
name: Password Exfiltration over SCIM application
description: |
  'detects suspicious sync events that occurred to applications using SCIM for user provisioning.'
requiredDataConnectors:
  - connectorId: Authomize
    dataTypes:
      - Authomize_v2_CL
tactics:
  - CredentialAccess
relevantTechniques:
  - T1555
  - T1040
  - T1552
  - T1555.003
  - T1552.005
query: |
  union withsource=_TableName Authomize_v2_CL
  | extend EventID = id_s
  | extend Policy = policy_name_s
  | extend Severity = severity_s
  | extend Description = description_s
  | extend Recommendation = recommendation_s
  | extend URL = url_s
  | extend Tactics = tactics_s
  | where Policy contains "Password Exfiltration over SCIM"
  | project EventID, Policy, Severity, Description, Recommendation, URL, Category, Tactics
  | extend CloudApplication_0_Name = Policy
entityMappings:
  - entityType: CloudApplication
    fieldMappings:
      - identifier: Name
        columnName: Policy
version: 1.0.0
metadata:
    source:
        kind: Authomize
    author:
        name: Steven Riley
    support:
        tier: support@authomize.com