on: pull_request

jobs:
  pr_comment:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@master
        with:
          message: 'Thanks for submitting your PR to the Azure Sentinel GitHub repo! You should expect an initial response to your PR from the team within 7 days. Note that this response may be delayed during holiday periods.'
          GITHUB_TOKEN: ${{ secrets.WORKFLOW2 }}