id: 75ea5c39-93e5-489b-b1e1-68fa6c9d2d04
name: Attempts to sign in to disabled accounts by account name.
description: |
  (failed) attempts to sign in to disabled accounts summarized by
  account name. An alert is generated if this behaviour is seen across 
  multiple Azure Applications.
severity: Medium
requiredDataConnectors:
  - connectorId: AzureActiveDirectory
    dataTypes:
      - SigninLogs
queryFrequency: 24h
queryPeriod: 24h
triggerOperator: gt
triggerThreshold: 0
tactics:
  - InitialAccess
query: |

  SigninLogs
  | where TimeGenerated >= ago(30d)
  | where ResultType == "50057"
  | where ResultDescription == "User account is disabled. The account has been disabled by an administrator."
  | summarize count(), applicationCount=dcount(AppDisplayName), applicationSet=makeset(AppDisplayName) by UserPrincipalName
  | where applicationCount >= 3

