id: "[concat(resourceId('Microsoft.OperationalInsights/workspaces/providers', parameters('workspace'), 'Microsoft.SecurityInsights'),'/alertRules/6e9e1975-6d85-4387-bd30-3881c66e302e')]"
name: "[concat(parameters('workspace'),'/Microsoft.SecurityInsights/6e9e1975-6d85-4387-bd30-3881c66e302e')]"
type: Microsoft.OperationalInsights/workspaces/providers/alertRules
kind: Scheduled
apiVersion: 2022-11-01-preview
properties:
  displayName: Brand Abuse
  description: New Brand Abuse with severity High found
  severity: High
  enabled: true
  query: |-
    CBSLogPolling_1_CL
    | where severity_s == "High"
    | where type_s == "Brand Abuse"
    | where status_s != "Closed" or status_s != "Resolved" 
    | where remarks_s == "New Brand Abuse with severity High found"
  queryFrequency: PT5M
  queryPeriod: PT5M
  triggerOperator: GreaterThan
  triggerThreshold: 0
  suppressionDuration: PT5H
  suppressionEnabled: false
  startTimeUtc: 
  tactics:
  - DefenseEvasion
  techniques: []
  alertRuleTemplateName: 
  incidentConfiguration:
    createIncident: true
    groupingConfiguration:
      enabled: true
      reopenClosedIncident: false
      lookbackDuration: PT5H
      matchingMethod: AllEntities
      groupByEntities: []
      groupByAlertDetails: []
      groupByCustomDetails: []
  eventGroupingSettings:
    aggregationKind: AlertPerResult
  alertDetailsOverride: 
  customDetails: {}
  entityMappings:
  - entityType: URL
    fieldMappings:
    - identifier: Url
      columnName: subject_s
  sentinelEntitiesMappings: 
  templateVersion: 
