id: "[concat(resourceId('Microsoft.OperationalInsights/workspaces/providers', parameters('workspace'), 'Microsoft.SecurityInsights'),'/alertRules/2caf81cf-a419-4d56-91da-67368f2e73d2')]"
name: "[concat(parameters('workspace'),'/Microsoft.SecurityInsights/2caf81cf-a419-4d56-91da-67368f2e73d2')]"
type: Microsoft.OperationalInsights/workspaces/providers/alertRules
kind: Scheduled
apiVersion: 2022-11-01-preview
properties:
  displayName: Exposed User List
  description: Exposed User List
  severity: High
  enabled: true
  query: HVLogPolling_1_CL | where severity_s == "high" | where progress_status_s == "New" | where status_s != "inactive"  | where issue_name_s == "Exposed User List"
  queryFrequency: PT5M
  queryPeriod: PT5M
  triggerOperator: GreaterThan
  triggerThreshold: 0
  suppressionDuration: PT5H
  suppressionEnabled: false
  startTimeUtc: 
  tactics: []
  techniques: []
  alertRuleTemplateName: 
  incidentConfiguration:
    createIncident: true
    groupingConfiguration:
      enabled: false
      reopenClosedIncident: false
      lookbackDuration: PT5H
      matchingMethod: AllEntities
      groupByEntities: []
      groupByAlertDetails: []
      groupByCustomDetails: []
  eventGroupingSettings:
    aggregationKind: SingleAlert
  alertDetailsOverride: 
  customDetails: 
  entityMappings:
  - entityType: IP
    fieldMappings:
    - identifier: Address
      columnName: meta_resolved_ip_s
  - entityType: Host
    fieldMappings:
    - identifier: HostName
      columnName: meta_host_s
  - entityType: URL
    fieldMappings:
    - identifier: Url
      columnName: hackerview_link_s
  sentinelEntitiesMappings: 
  templateVersion: 
