id: "[concat(resourceId('Microsoft.OperationalInsights/workspaces/providers', parameters('workspace'), 'Microsoft.SecurityInsights'),'/alertRules/2f58535e-e92a-450f-8052-a905b8c340b1')]"
name: "[concat(parameters('workspace'),'/Microsoft.SecurityInsights/2f58535e-e92a-450f-8052-a905b8c340b1')]"
type: Microsoft.OperationalInsights/workspaces/providers/alertRules
kind: Scheduled
apiVersion: 2022-11-01-preview
properties:
  displayName: Exposed Admin Login Page
  description: Exposed Admin Login Page
  severity: Medium
  enabled: true
  query: HVLogPolling_1_CL | where severity_s == "medium" | where progress_status_s == "New" | where status_s != "inactive"  | where issue_name_s == "Exposed Admin Login Page"
  queryFrequency: PT5M
  queryPeriod: PT5M
  triggerOperator: GreaterThan
  triggerThreshold: 0
  suppressionDuration: PT5H
  suppressionEnabled: false
  startTimeUtc: 
  tactics: []
  techniques: []
  alertRuleTemplateName: 
  incidentConfiguration:
    createIncident: true
    groupingConfiguration:
      enabled: false
      reopenClosedIncident: false
      lookbackDuration: PT5H
      matchingMethod: AllEntities
      groupByEntities: []
      groupByAlertDetails: []
      groupByCustomDetails: []
  eventGroupingSettings:
    aggregationKind: SingleAlert
  alertDetailsOverride:
    alertDynamicProperties: []
  customDetails: 
  entityMappings:
  - entityType: IP
    fieldMappings:
    - identifier: Address
      columnName: meta_resolved_ip_s
  - entityType: URL
    fieldMappings:
    - identifier: Url
      columnName: hackerview_link_s
  - entityType: Host
    fieldMappings:
    - identifier: HostName
      columnName: meta_host_s
  sentinelEntitiesMappings: 
  templateVersion: 
