id: "[concat(resourceId('Microsoft.OperationalInsights/workspaces/providers', parameters('workspace'), 'Microsoft.SecurityInsights'),'/alertRules/32f4eb88-0d23-4185-8579-f1645412e9de')]"
name: "[concat(parameters('workspace'),'/Microsoft.SecurityInsights/32f4eb88-0d23-4185-8579-f1645412e9de')]"
type: Microsoft.OperationalInsights/workspaces/providers/alertRules
kind: Scheduled
apiVersion: 2022-11-01-preview
properties:
  displayName: SPF Policy Set to Soft Fail
  description: SPF Policy Set to Soft Fail
  severity: Low
  enabled: true
  query: HVLogPolling_1_CL | where severity_s == "low" | where progress_status_s == "New" | where status_s != "inactive"  | where issue_name_s == "SPF Policy Set to Soft Fail"
  queryFrequency: PT5M
  queryPeriod: PT5M
  triggerOperator: GreaterThan
  triggerThreshold: 0
  suppressionDuration: PT5H
  suppressionEnabled: false
  startTimeUtc: 
  tactics: []
  techniques: []
  alertRuleTemplateName: 
  incidentConfiguration:
    createIncident: true
    groupingConfiguration:
      enabled: false
      reopenClosedIncident: false
      lookbackDuration: PT5H
      matchingMethod: AllEntities
      groupByEntities: []
      groupByAlertDetails: []
      groupByCustomDetails: []
  eventGroupingSettings:
    aggregationKind: SingleAlert
  alertDetailsOverride: 
  customDetails: 
  entityMappings:
  - entityType: IP
    fieldMappings:
    - identifier: Address
      columnName: meta_resolved_ip_s
  - entityType: Host
    fieldMappings:
    - identifier: HostName
      columnName: meta_host_s
  - entityType: URL
    fieldMappings:
    - identifier: Url
      columnName: hackerview_link_s
  sentinelEntitiesMappings: 
  templateVersion: 
