id: "[concat(resourceId('Microsoft.OperationalInsights/workspaces/providers', parameters('workspace'), 'Microsoft.SecurityInsights'),'/alertRules/7bbe51fe-9c5f-4f54-a079-b84cc27737a1')]"
name: "[concat(parameters('workspace'),'/Microsoft.SecurityInsights/7bbe51fe-9c5f-4f54-a079-b84cc27737a1')]"
type: Microsoft.OperationalInsights/workspaces/providers/alertRules
kind: Scheduled
apiVersion: 2022-11-01-preview
properties:
  displayName: TLS Certificate Using Weak Cipher
  description: TLS Certificate Using Weak Cipher
  severity: Medium
  enabled: true
  query: HVLogPolling_1_CL | where severity_s == "medium" | where progress_status_s == "New" | where status_s != "inactive"  | where issue_name_s == "TLS Certificate Using Weak Cipher"
  queryFrequency: PT5H
  queryPeriod: PT5H
  triggerOperator: GreaterThan
  triggerThreshold: 0
  suppressionDuration: PT5H
  suppressionEnabled: false
  startTimeUtc: 
  tactics: []
  techniques: []
  alertRuleTemplateName: 
  incidentConfiguration:
    createIncident: true
    groupingConfiguration:
      enabled: false
      reopenClosedIncident: false
      lookbackDuration: PT5H
      matchingMethod: AllEntities
      groupByEntities: []
      groupByAlertDetails: []
      groupByCustomDetails: []
  eventGroupingSettings:
    aggregationKind: SingleAlert
  alertDetailsOverride: 
  customDetails: 
  entityMappings:
  - entityType: IP
    fieldMappings:
    - identifier: Address
      columnName: meta_resolved_ip_s
  - entityType: URL
    fieldMappings:
    - identifier: Url
      columnName: hackerview_link_s
  - entityType: Host
    fieldMappings:
    - identifier: HostName
      columnName: meta_host_s
  sentinelEntitiesMappings: 
  templateVersion: 
