id: a1a06ba2-87f8-11ec-a8a3-0242ac120002
name: Large Scale Malware Deployment via GPO Scheduled Task Modification
description: |
  'This query detects lateral movement using GPO scheduled task usually used to deploy ransomware at scale.
   It monitors whether a scheduled task is modified within the Sysvol folder in GPO.
   Ref: https://bogusecurity.com/2019/12/26/persistence-and-execution-at-scale-via-gpo-scheduled-task/'
requiredDataConnectors:
  - connectorId: SecurityEvents
    dataTypes:
      - SecurityEvent
  - connectorId: WindowsForwardedEvents
    dataTypes:
      - WindowsEvent
tactics:
  - LateralMovement
relevantTechniques:
  - T1484
query: |
 union isfuzzy=true 
 (SecurityEvent
    | where EventID == 5145 
    | where ShareName == "\\\\*\\SYSVOL" and RelativeTargetName endswith "ScheduledTasks.xml" and AccessList contains "%%4417"
    | summarize StartTime = min(TimeGenerated), EndTime = max(TimeGenerated) by EventID, Computer, SubjectDomainName, SubjectUserName, SubjectLogonId, ShareName, RelativeTargetName, AccessList, IpAddress
    ),
    (WindowsEvent
    | where EventID == 5145 and EventData has "\\\\*\\SYSVOL"  and EventData has "ScheduledTasks.xml"  and EventData has "%%4417" 
    | extend ShareName = tostring(EventData.ShareName)
    | where ShareName == "\\\\*\\SYSVOL"     
    | extend RelativeTargetName= tostring(EventData.RelativeTargetName)
    | where RelativeTargetName endswith "ScheduledTasks.xml"  
    | extend AccessList= tostring(EventData.AccessList)
    | where AccessList contains "%%4417"
    | extend   SubjectDomainName = tostring(EventData.SubjectDomainName)
    | extend   SubjectUserName = tostring(EventData.SubjectUserName)
    | extend   SubjectLogonId = tostring(EventData.SubjectLogonId)
    | extend   IpAddress = tostring(EventData.IpAddress)
    | summarize StartTime = min(TimeGenerated), EndTime = max(TimeGenerated) by EventID, Computer, SubjectDomainName, SubjectUserName, SubjectLogonId, ShareName, RelativeTargetName, AccessList, IpAddress)
