id: 9b555f36-6d50-4f08-ada1-bef16644b981
name: Rundll32 or cmd Executing Application from Explorer - Potential Malware Execution Chain
description: |
  'Identifies when rundll32 or cmd.exe is utilized to launch a malicious DLL or executable from explorer.exe. Indicative of a cmd window or LNK file executing a program or malware due to a user clicking on a file.'
requiredDataConnectors:
  - connectorId: SecurityEvent
    dataTypes:
      - SecurityEvent
query: |
  SecurityEvent
  | where ParentProcessName has "explorer.exe" 
  | where Process has_any (
    "wscript.exe",
    "rundll32.exe",
    "explorer.exe",
    "cmd.exe"
    )
  | where (CommandLine has_any (
    "explorer",
    "rundll32"
    ) and CommandLine has_any (
    ".dll,",
    ".dll "
    )) or (CommandLine has "cmd.exe" and CommandLine matches regex "\\/[Cc] +[Ss][Tt][Aa][Rr][Tt].*\\.exe")
  | project TimeGenerated, Computer, tostring(EventID), ParentProcessName, NewProcessName, CommandLine, SubjectUserName, SourceComputerId, processID=tolong(NewProcessId), parentProcessID=tolong(ProcessId), EventData| order by TimeGenerated