alertDetailsOverride: null
customDetails:
    SAP_User: User
description: "Identifies changes for client configuration such as: Client role, Changes\
    \ recording mode. \n\nSource Action:  Perofrm client configurations changes using\
    \ SCC4 transaction code. \n\n*Data Sources: SAPcon -  Audit Log*"
entityMappings:
-   entityType: Account
    fieldMappings:
    -   columnName: Email
        identifier: FullName
-   entityType: IP
    fieldMappings:
    -   columnName: TerminalIPv6
        identifier: Address
-   entityType: Host
    fieldMappings:
    -   columnName: Host
        identifier: FullName
-   entityType: CloudApplication
    fieldMappings:
    -   columnName: SystemID
        identifier: Name
    -   columnName: ClientID
        identifier: AppId
    -   columnName: Instance
        identifier: InstanceName
eventGroupingSettings:
    aggregationKind: AlertPerResult
id: 4258c51d-59db-4502-9b02-fb2ab20e97d4
kind: Scheduled
name: SAP - Client Configuration Change
query: "// Audit Log Classes - Client Change Configuration\r\nlet AuditClasses = dynamic(['EU2']);\
    \ // Relevent message\r\nSAPAuditLog \r\n| where MessageID in (AuditClasses)\r\
    \n| project-rename ClientIDTemp = ClientID \n| project-rename ClientID= Variable1\
    \ \r\n| parse Variable2 with Currency \"|\" ClientRole \"|\" RecordingChanges\
    \ \"|\" CrossClientObjectChanges \"|\" ClientCopyProtectionLevel \"|\" ProtectionSAPUpgrade\
    \ \"|\" CATTeCATT \"|\"  LockedforCopy // Parse every object before the | char\
    \ \r\n| project TimeGenerated, Instance, SystemID, User, ClientID, \r\nCurrency,ClientRole,RecordingChanges,CrossClientObjectChanges,ClientCopyProtectionLevel,CATTeCATT,LockedforCopy,ProtectionSAPUpgrade,\r\
    \nMessageText, Email, TerminalIPv6,  Host\r\n"
queryFrequency: 5h
queryPeriod: 5h
relevantTechniques: ''
requiredDataConnectors:
-   connectorId: SAP
    dataTypes:
    - SAPAuditLog
severity: High
tactics:
- DefenseEvasion
- Exfiltration
- Persistence
triggerOperator: gt
triggerThreshold: 0
version: 2.0.15
