id: f4da8e9d-3515-4a2a-8cf0-43334fa29d91
name: SAP - System Configuration Change
description: |
    'Identifies changes for system configuration.
    Source Action:  Adapt system change options or software components modifcation using SE06 transaction code.
    *Data Sources: SAPcon -  Audit Log*'
severity: High
requiredDataConnectors:
 -   connectorId: SAP
queryFrequency: 1h
queryPeriod: 1h
triggerOperator: gt
triggerThreshold: 0
tactics:
 - Exfiltration
 - DefenseEvasion
 - Persistence
query: |
    // Audit Log Classes - System Change Configuration
    let AuditClasses = dynamic(['EU1']); // Relevant message
    SAPAuditLog
    | where MessageID in (AuditClasses)
    | project
    // Details
    TimeGenerated,Instance, ClientID ,SystemID, User, TransactionCode, SoftwareComponent = Variable1, NewModifiabilityStatus = Variable2, MessageText,
    Email, TerminalIPv6, Host
customDetails:
    SAP_User: User
entityMappings:
 -  entityType: Account
    fieldMappings:
     -  identifier: FullName
        columnName: Email
 -  entityType: IP
    fieldMappings:
     -  identifier: Address
        columnName: TerminalIPv6
 -  entityType: Host
    fieldMappings:
     -  identifier: FullName
        columnName: Host
 -  entityType: CloudApplication
    fieldMappings:
     -  identifier: Name
        columnName: SystemID
     -  identifier: AppId
        columnName: ClientID
     -  identifier: InstanceName
        columnName: Instance
eventGroupingSettings:
    aggregationKind: SingleAlert
kind: Scheduled
version: 2.0.19
