alertDetailsOverride: null
customDetails:
    SAP_User: User
description: ' Identifies Insecure FTP servers configuration - FTP Whitelist is empty
    / Contains Placeholders.


    Source Action: Do not maintain / maintain values which contains placeholders in
    table SAPFTP_SERVERS using maintenance view SAPFTP_SERVERS_V. (SM30)


    *Data Sources: SAPcon -  Audit Log*'
entityMappings:
-   entityType: Account
    fieldMappings:
    -   columnName: Email
        identifier: FullName
-   entityType: IP
    fieldMappings:
    -   columnName: TerminalIPv6
        identifier: Address
-   entityType: Host
    fieldMappings:
    -   columnName: Host
        identifier: FullName
-   entityType: CloudApplication
    fieldMappings:
    -   columnName: SystemID
        identifier: Name
    -   columnName: ClientID
        identifier: AppId
    -   columnName: Instance
        identifier: InstanceName
eventGroupingSettings:
    aggregationKind: SingleAlert
id: 78fbdc7d-6136-4afc-9cc5-5e5aff1563ae
kind: Scheduled
name: SAP - Insecure FTP servers configuration
query: "// Define variables\r\nlet AuditClasses = dynamic(['DU1', 'DU2']); // Messages\
    \ of FTP Whitelist is empty / Contains Placeholders\r\n// Query logic\r\nSAPAuditLog\r\
    \n| where MessageID in (AuditClasses)\r\n| project TimeGenerated, Instance, SystemID,\
    \ ClientID, User, Email, TerminalIPv6, Host, Reason = MessageText"
queryFrequency: 6h
queryPeriod: 6h
relevantTechniques: ''
requiredDataConnectors:
-   connectorId: SAP
    dataTypes:
    - SAPAuditLog
severity: Medium
tactics:
- InitialAccess
- CommandAndControl
triggerOperator: gt
triggerThreshold: 0
version: 2.0.15
