alertDetailsOverride:
    alertDescriptionFormat: "An SAP audit log event with {{MissingMessageIDs}}{{ComingFromSystemIDs}},\
        \ for which a configuration in the SAPAuditLogConfigurator watchlist could\
        \ not be found.</br>\nThe SAPAuditLogConfigurator watchlist allows for dynamically\
        \ alerting on SAP audit log events. </br>\nRecommended solution - go to the\
        \ SAPAuditLogConfigurator and add the missing SAP audit log message ID.  \n\
        Specify a severity level of medium or high to have this message ID covered\
        \ by the alerts based on rule \"SAP - Dynamic Alerts for Configured Audit\
        \ Log Events\".\n\n"
    alertDisplayNameFormat: SAP - Missing configuration for SAP's audit log, {{ComingFromSystemIDs}}
    alertSeverityColumnName: ClientID
    alertTacticsColumnName: ClientID
customDetails:
    SAPAuditLogMessageID: MissingMessageID
description: "An SAP audit log event has occurred bearing a message ID which was not\
    \ maintained in the SAP_Dynamic_Audit_Log_Monitor_Configuration watchlist.\nThe\
    \ SAP_Dynamic_Audit_Log_Monitor_Configuration watchlist allows for dynamically\
    \ alerting on SAP audit log events. \nRecommended solution - go to the SAP_Dynamic_Audit_Log_Monitor_Configuration\
    \ and add the missing SAP audit log message ID.  Specify a severity level of medium\
    \ or high to have this message ID covered by the alerts based on rule \"Dynamic\
    \ Security Audit Log Monitor\".\n"
entityMappings:
-   entityType: CloudApplication
    fieldMappings:
    -   columnName: ComingFromSystemID
        identifier: Name
    -   columnName: ClientID
        identifier: AppId
eventGroupingSettings:
    aggregationKind: SingleAlert
id: b0594a30-5da4-4eca-89af-cb8ad111d697
kind: Scheduled
name: SAP - Missing configuration in the Dynamic Security Audit Log Monitor
query: "let MissingMessagesinSystems = SAPAuditLog\r\n| summarize LastSeenMessageOn\
    \ = arg_max(TimeGenerated, MessageID) by MessageID, SystemID, ClientID\r\n| join\
    \ kind = leftanti (SAPAuditLogConfiguration(SelectedSeverities =  dynamic([\"\
    All Severities\"])) | summarize by MessageID) on MessageID\r\n| project-keep LastSeenMessageOn,\
    \ MessageID, SystemID, ClientID\r\n| project-rename MissingMessageID = MessageID,\
    \ ComingFromSystemID = SystemID\r\n| extend Dummy = 1;\r\nlet MissingSummary =\
    \ MissingMessagesinSystems\r\n| summarize\r\n  ComingFromSystemIDs =  make_set(ComingFromSystemID)\r\
    \n, MissingMessageIDs = make_set(MissingMessageID)\r\n| extend ComingFromSystemIDs\
    \ = iff(array_length(ComingFromSystemIDs) > 1, strcat('Systems ', strcat_array(ComingFromSystemIDs,\"\
    , \")), strcat('System ',strcat_array(ComingFromSystemIDs,\", \")))\r\n| extend\
    \ MissingMessageIDs = iff(array_length(MissingMessageIDs) > 1, strcat('Message\
    \ IDs ', strcat_array(MissingMessageIDs,\", \"), \" have occured in \"), strcat('Message\
    \ ID ',strcat_array(MissingMessageIDs,\", \"), \" has occured in \"))\r\n| extend\
    \ Dummy = 1;\r\nMissingMessagesinSystems | join kind= inner MissingSummary on\
    \ Dummy\r\n| project-away Dummy, Dummy1"
queryFrequency: 1d
queryPeriod: 1d
relevantTechniques: ''
requiredDataConnectors:
-   connectorId: SAP
    dataTypes:
    - SAPAuditLogConfiguration
    - SAPAuditLog
severity: Informational
tactics: []
triggerOperator: gt
triggerThreshold: 0
version: 2.0.15
