alertDetailsOverride: null
customDetails:
    SAP_User: User
description: |
    Identifies changes for system configuration.

    Source Action:  Adapt system change options or software components modifcation using SE06 transaction code.

    *Data Sources: SAPcon -  Audit Log*
entityMappings:
-   entityType: Account
    fieldMappings:
    -   columnName: Email
        identifier: FullName
-   entityType: IP
    fieldMappings:
    -   columnName: TerminalIPv6
        identifier: Address
-   entityType: Host
    fieldMappings:
    -   columnName: Host
        identifier: FullName
-   entityType: CloudApplication
    fieldMappings:
    -   columnName: SystemID
        identifier: Name
    -   columnName: ClientID
        identifier: AppId
    -   columnName: Instance
        identifier: InstanceName
eventGroupingSettings:
    aggregationKind: SingleAlert
id: f4da8e9d-3515-4a2a-8cf0-43334fa29d91
kind: Scheduled
name: SAP - System Configuration Change
query: |
    // Audit Log Classes - System Change Configuration
    let AuditClasses = dynamic(['EU1']); // Relevant message
    SAPAuditLog
    | where MessageID in (AuditClasses)
    | project
    // Details
    TimeGenerated,Instance, ClientID ,SystemID, User, TransactionCode, SoftwareComponent = Variable1, NewModifiabilityStatus = Variable2, MessageText,
    Email, TerminalIPv6, Host
queryFrequency: 1h
queryPeriod: 1h
relevantTechniques: ''
requiredDataConnectors:
-   connectorId: SAP
    dataTypes:
    - SAPAuditLog
severity: High
tactics:
- Exfiltration
- DefenseEvasion
- Persistence
triggerOperator: gt
triggerThreshold: 0
version: 2.0.19
