alertDetailsOverride: null
customDetails:
    SAP_User: User
description: 'Idenitifes changes for configuration in Securiy Audit Log


    Source Action: change any  Security Audit Log Configuration using SM19/RSAU_CONFIG.
    (Filters/Status/Recording mode etc..)


    *Data Sources: SAPcon -  Audit Log*'
entityMappings:
-   entityType: IP
    fieldMappings:
    -   columnName: TerminalIPv6
        identifier: Address
-   entityType: Account
    fieldMappings:
    -   columnName: Email
        identifier: FullName
-   entityType: Host
    fieldMappings:
    -   columnName: Host
        identifier: FullName
-   entityType: CloudApplication
    fieldMappings:
    -   columnName: SystemID
        identifier: Name
    -   columnName: Instance
        identifier: InstanceName
eventGroupingSettings:
    aggregationKind: SingleAlert
id: ea0f2cc5-9ee4-45b0-bc19-fdbdf37b4db4
kind: Scheduled
name: SAP - Security Audit Log Configuration Change
query: "// Audit Log Classes - Audit Log Configuration Events\r\nlet AuditClasses\
    \ = dynamic(['AUE','AUF','AUI','AUJ','FU0','E05']); // Relevant messages\r\nSAPAuditLog\
    \ \r\n| where MessageID in (AuditClasses)\r\n| project \r\n// Details\r\nTimeGenerated,\
    \ Instance, SystemID, User, MessageText,\r\nEmail, TerminalIPv6, Host"
queryFrequency: 6h
queryPeriod: 6h
relevantTechniques: ''
requiredDataConnectors:
-   connectorId: SAP
    dataTypes:
    - SAPAuditLog
severity: Medium
tactics:
- Persistence
- Exfiltration
- DefenseEvasion
triggerOperator: gt
triggerThreshold: 0
version: 2.0.15
