
id: 43c6318d-fa5e-49da-8b7a-a5a7c138de28
name: Known Bad Process (NRT)
type: Microsoft.OperationalInsights/workspaces/providers/alertRules
kind: NRT
apiVersion: 2022-10-01-preview
properties:
  displayName: Known Bad Process (NRT)
  description: ''
  severity: High
  enabled: true
  queryFrequency: 1m
  queryPeriod: 1m
  query: |+
    SuperShieldActivity
    | where Severity == 0
    | where IsUnknown == 0 or IsUnknown == "false"
    | where TimeGenerated > ago(5m)

  suppressionDuration: PT5H
  suppressionEnabled: false
  tactics:
  - Execution
  techniques:
  alertRuleTemplateName:
  incidentConfiguration:
    createIncident: true
    groupingConfiguration:
      enabled: true
      reopenClosedIncident: false
      lookbackDuration: PT30M
      matchingMethod: Selected
      groupByEntities:
      - FileHash
      groupByAlertDetails:
      groupByCustomDetails:
  alertDetailsOverride:
    alertDisplayNameFormat: "{{Product}}{{ProcessName}} {{FileName}}"
  customDetails:
    deviceExternal: DeviceExternalID
    product: Product
    groupName: GroupName
    group: GroupID
    osPlatform: OSPlatform
    company: CompanyID
    companyName: CompanyName
    account: AccountID
    md5: MD5
    processName: ProcessName
  entityMappings:
  - entityType: IP
    fieldMappings:
    - identifier: Address
      columnName: DeviceAddress
  - entityType: Host
    fieldMappings:
    - identifier: HostName
      columnName: Host
  - entityType: FileHash
    fieldMappings:
    - identifier: Value
      columnName: FileHash
  - entityType: File
    fieldMappings:
    - identifier: Directory
      columnName: FilePath
    - identifier: Name
      columnName: FileName
  - entityType: Process
    fieldMappings:
    - identifier: CommandLine
      columnName: CmdLineArgs
  sentinelEntitiesMappings: