id: 81cbf6ad-e86d-4976-8746-6f0d1877bb04
name: Unknown Process (NRT)
type: Microsoft.OperationalInsights/workspaces/providers/alertRules
kind: NRT
apiVersion: 2022-10-01-preview
properties:
  displayName: Unknown Process (NRT)
  description: ''
  severity: Medium
  enabled: true
  queryFrequency:
  queryPeriod:
  query: |+
    SuperShieldActivity
    | where Severity == 0
    | where IsUnknown == 1 or IsUnknown == "true"
    | where TimeGenerated > ago(5m)

  suppressionDuration: PT5H
  suppressionEnabled: false
  tactics:
  - Execution
  techniques:
  alertRuleTemplateName:
  incidentConfiguration:
    createIncident: true
    groupingConfiguration:
      enabled: true
      reopenClosedIncident: false
      lookbackDuration: PT30M
      matchingMethod: Selected
      groupByEntities:
      - FileHash
      groupByAlertDetails:
      groupByCustomDetails:
  alertDetailsOverride:
    alertDisplayNameFormat: "{{Product}}{{ProcessName}} {{FileName}}"
  customDetails:
    deviceExternal: DeviceExternalID
    product: Product
    groupName: GroupName
    group: GroupID
    osPlatform: OSPlatform
    company: CompanyID
    companyName: CompanyName
    account: AccountID
    md5: MD5
    processName: ProcessName
  entityMappings:
  - entityType: IP
    fieldMappings:
    - identifier: Address
      columnName: DeviceAddress
  - entityType: Host
    fieldMappings:
    - identifier: HostName
      columnName: Host
  - entityType: FileHash
    fieldMappings:
    - identifier: Value
      columnName: FileHash
  - entityType: File
    fieldMappings:
    - identifier: Directory
      columnName: FilePath
    - identifier: Name
      columnName: FileName
  - entityType: Process
    fieldMappings:
    - identifier: CommandLine
      columnName: CmdLineArgs
  sentinelEntitiesMappings: