jobs:
- job: "AsimParsersValidations"
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - task: AzurePowerShell@5
    inputs:
      azureSubscription: eco-connector-test-service-connection
      scriptType: filePath
      scriptPath: .script/tests/asimParsersTest/runAsimTesters.ps1
      azurePowerShellVersion: latestVersion
      pwsh: true
