trigger:
  branches:
    include:
      - '*'  # This includes all branches
pool:
  vmImage: 'ubuntu-latest'
jobs:
- job: ASIMSchemaDataTester
  displayName: 'Run ASIM testers on "eco-connector-test" workspace'
  steps:
  - checkout: self
    persistCredentials: false
    fetchDepth: 0  # Fetch full repository history

  - script: |
      set -e  # Exit on error
      echo "Running Azure CLI commands..."
      # Example command to list resource groups
      az group list
    displayName: 'Run Azure CLI commands'

  - script: |
      git config --local user.name "azure-pipelines[bot]"
      git config --local user.email "<>"
    displayName: 'Setup git config'

  - script: |
      git merge origin/master
      Conflicts=$(git ls-files -u | wc -l)
      if [ "$Conflicts" -gt 0 ] ; then
        echo "There is a merge conflict. Aborting"
        git merge --abort
        exit 1
      fi
    displayName: 'Merge master into pull request branch'

  - task: AzurePowerShell@5
    inputs:
      azureSubscription: 'ASIM-SchemaDataTester-ServiceConnection'
      ScriptType: 'InlineScript'
      Inline: |
        & ".script/tests/asimParsersTest/runAsimTesters.ps1"
      FailOnStandardError: false
      ErrorActionPreference: 'continue'
      azurePowerShellVersion: 'latest'
