trigger:
  branches:
    include:
      - '*'  # This includes all branches
  paths:
    include:
      - 'Parsers/ASimDns/Parsers/**'
      - 'Parsers/ASimNetworkSession/Parsers/**'
      - 'Parsers/ASimWebSession/Parsers/**'
      - 'Parsers/ASimProcessEvent/Parsers/**'
      - 'Parsers/ASimAuditEvent/Parsers/**'
      - 'Parsers/ASimAuthentication/Parsers/**'
      - 'Parsers/ASimFileEvent/Parsers/**'
      - 'Parsers/ASimRegistryEvent/Parsers/**'
      - 'Parsers/ASimUserManagement/Parsers/**'
      - 'Parsers/ASimDhcpEvent/Parsers/**'

jobs:
- job: ASIMSchemaDataTester
  displayName: 'Run ASIM testers on "eco-connector-test" workspace'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - checkout: self
      persistCredentials: false
      fetchDepth: 0  # Fetch full repository history
    # Add more steps here...
