jobs:
- job: "ASIMSchemaDataTester"
  displayName: 'Run ASIM testers on "varunlab-workspace-for-sentinel" workspace'
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - script: |
      echo "Checking for ASIM Parser files in the pull request..."

      # Set variables
      REPO="Azure/Azure-Sentinel"
      PR_ID=$(System.PullRequest.PullRequestNumber)
      GITHUB_TOKEN=$(Github_PAT_ASIM_Schema_Data_Tester)

      # Fetch the list of changed files using GitHub REST API
      changed_files_json=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "$api_url")

      # Check if the request was successful
      if echo $changed_files_json | jq -e . >/dev/null 2>&1; then
        echo "Successfully fetched changed files."
      else
        echo "Failed to fetch changed files. Response:"
        echo $changed_files_json
        exit 1
      fi

      # Extract the list of filenames using jq
      changed_files=$(echo $changed_files_json | jq -r '.[].filename')

      # Initialize the variable indicating if relevant files are found
      files_changed=false

      # Check each changed file against the specified paths
      for file in $changed_files; do
        if [[ $file == Parsers/ASimDns/Parsers/* ]] || \
          [[ $file == Parsers/ASimNetworkSession/Parsers/* ]] || \
          [[ $file == Parsers/ASimWebSession/Parsers/* ]] || \
          [[ $file == Parsers/ASimProcessEvent/Parsers/* ]] || \
          [[ $file == Parsers/ASimAuditEvent/Parsers/* ]] || \
          [[ $file == Parsers/ASimAuthentication/Parsers/* ]] || \
          [[ $file == Parsers/ASimFileEvent/Parsers/* ]] || \
          [[ $file == Parsers/ASimRegistryEvent/Parsers/* ]] || \
          [[ $file == Parsers/ASimUserManagement/Parsers/* ]] || \
          [[ $file == Parsers/ASimDhcpEvent/Parsers/* ]]; then
          echo "Found changed file $file in specified locations."
          files_changed=true
          break
        fi
      done

      # Output the result
      echo "##vso[task.setvariable variable=files_changed]$files_changed"
      echo "ASIM Parser changes detected: $files_changed"
    displayName: 'Check for Changes to ASIM Parser Files in the Pull Request'
    env:
      Github_PAT_ASIM_Schema_Data_Tester: $(Github_PAT_ASIM_Schema_Data_Tester)

  - checkout: self
    persistCredentials: false
    fetchDepth: 0  # Fetch full repository history
    condition: eq(variables['files_changed'], true)

  - script: |
      git config --local user.name "azure-pipelines[bot]"
      git config --local user.email "<>"
    displayName: 'Setup git config'
    condition: and(succeeded(), eq(variables['files_changed'], 'true'))

  - script: |
      git merge origin/master
      Conflicts=$(git ls-files -u | wc -l)
      if [ "$Conflicts" -gt 0 ] ; then
        echo "There is a merge conflict. Aborting"
        git merge --abort
        exit 1
      fi
    displayName: 'Merge master into pull request branch'
    condition: and(succeeded(), eq(variables['files_changed'], 'true'))

  - task: AzurePowerShell@5
    inputs:
      azureSubscription: 'ASIM-SchemaDataTester-ServiceConnection'
      ScriptType: 'InlineScript'
      Inline: |
        & ".script/tests/asimParsersTest/runAsimTesters.ps1"
      FailOnStandardError: false
      ErrorActionPreference: 'continue'
      azurePowerShellVersion: 'latest'
    condition: and(succeeded(), eq(variables['files_changed'], 'true'))
