jobs:
- job: "ASIMSchemaDataTester"
  displayName: 'Run ASIM testers on "eco-connector-test" workspace'
  
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - script: |
      echo "Checking for changed files in the pull request..."

      # Install jq for JSON processing
      sudo apt-get update
      sudo apt-get install -y jq

      # Get the organization name and project name from environment variables
      ORG_NAME=$(System.CollectionUri)
      PROJECT_NAME=$(System.TeamProject)

      # Get the repository ID and pull request ID from environment variables
      REPO_ID=$(Build.Repository.ID)
      PR_ID=$(System.PullRequest.PullRequestId)

      echo "Organization: $ORG_NAME"
      echo "Project: $PROJECT_NAME"
      echo "Repository: $REPO_ID"
      echo "Pull Request ID: $PR_ID"

      # Fetch the list of changed files in the PR
      changed_files=$(az repos pr list --id $PR_ID --repository-id $REPO_ID --org $ORG_NAME --project $PROJECT_NAME --query 'changes[].item.path' -o tsv)

      echo "Changed files: $changed_files"

      # Initialize the variable indicating if relevant files are found
      files_changed=false

      # Check each changed file against the specified paths
      for file in $changed_files; do
        if [[ $file == Parsers/ASimDns/Parsers/* ]] || \
           [[ $file == Parsers/ASimNetworkSession/Parsers/* ]] || \
           [[ $file == Parsers/ASimWebSession/Parsers/* ]] || \
           [[ $file == Parsers/ASimProcessEvent/Parsers/* ]] || \
           [[ $file == Parsers/ASimAuditEvent/Parsers/* ]] || \
           [[ $file == Parsers/ASimAuthentication/Parsers/* ]] || \
           [[ $file == Parsers/ASimFileEvent/Parsers/* ]] || \
           [[ $file == Parsers/ASimRegistryEvent/Parsers/* ]] || \
           [[ $file == Parsers/ASimUserManagement/Parsers/* ]] || \
           [[ $file == Parsers/ASimDhcpEvent/Parsers/* ]]; then
