jobs:
- job: "IdChangeValidation"
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      verbose: false
  - script: 'npm install simple-git && npm run tsc && node .script/idChangeValidator.js'
    displayName: 'Id change Validation'