jobs:
- job: "IdTestChangeValidation"
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      verbose: false
  - script: 'npm install simple-git && node .script/idValidator.js'
    displayName: 'Id change Validation'