id: 4f19d4e3-ec5f-4abc-9e61-819eb131758c
name: AWS - Changes to Security Group ingress and egress settings
description: |
  'Monitoring changes to AWS Security Group ingress and egress settings.
  More information: https://medium.com/@GorillaStack/the-most-important-aws-cloudtrail-security-events-to-track-a5b9873f8255'
severity: Low
requiredDataConnectors:
  - connectorId: AWS
    dataTypes:
      - AWSCloudTrail
queryFrequency: 1d
queryPeriod: 1d
triggerOperator: gt
triggerThreshold: 0
tactics:
  - LateralMovement
  - PrivilegeEscalation
query: |

  let timeframe = 1d;
  AWSCloudTrail
  | where TimeGenerated >= ago(timeframe)
  | where EventName == "AuthorizeSecurityGroupEgress"
       or EventName == "AuthorizeSecurityGroupIngress"
       or EventName == "RevokeSecurityGroupEgress"
       or EventName == "RevokeSecurityGroupIngress"
  | project TimeGenerated, EventName, EventTypeName, UserIdentityAccountId, UserIdentityPrincipalid, UserAgent, UserIdentityUserName, SessionMfaAuthenticated, SourceIpAddress, AWSRegion, EventSource, AdditionalEventData, ResponseElements
