name: Comment on PR

# Controls when the action will run. 
on: pull_request

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: Reminds submitter of expected response time to PR
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@master
        with:
          message: 'Thanks for submitting your PR to the Azure Sentinel GitHub repo! 

You should expect an initial response to your PR within 7 days. Note that this response may be delayed during holiday periods.'
          
          WORKFLOW: ${{ secrets.WORKFLOW }}
