
# name: Overwrite some file

# on:
#   pull_request:
#   push:

# jobs:
# # below is also working code
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Get branch name
#         id: branch-name
#         uses: tj-actions/branch-names@v6
      
#       - name: Running on a pull request branch.
#         if: steps.branch-name.outputs.is_default == 'false'
#         run: |
#           echo "Running on pr: ${{ steps.branch-name.outputs.current_branch }}"

#       - name: Checkout code
#         uses: actions/checkout@v3

  #below is the working code
      # - name: Overwrite file
      #   uses: "DamianReeves/write-file-action@master"
      #   with:
      #     path: "./Sample Data/sampleDataFile_new.json"
      #     write-mode: overwrite
      #     contents: |
      #       console.log('some contents')
              
      # - name: Commit & Push
      #   if: steps.branch-name.outputs.is_default == 'false'
      #   uses: Andro999b/push@v1.3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: "${{ steps.branch-name.outputs.current_branch }}"
      #     force: true
      #     message: 'Overwritten by Github Actions - ${date}'