name: test workflow

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  test-job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # check out and run the script
    steps:
      - name: Generate a token
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
        with:
          app_id: ${{ secrets.APPLICATION_ID }}
          private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}

      - name: Add Label Notification
        uses: actions/github-script@v6
        env:
          APPTOKEN: ${{ steps.generate_token.outputs.token }}
        with:
          github-token: ${{ env.APPTOKEN }}
          script: |
            github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['test']
            })